/**
 * Building Modeler — Core Type System
 *
 * Hierarchy mirrors IES VE ModelIT decomposition:
 *   BuildingModel → StoreyLayer → Space → Surface → Opening
 *
 * All geometry is stored in world metres, Y-up coordinate system.
 * 2D footprints live in the XZ plane (X = east, Z = south).
 * Vertical axis is Y.
 */

// ─── Primitives ──────────────────────────────────────────────────────────────

export interface Point2D {
  x: number // metres, east
  z: number // metres, south  (note: Z not Y, keeps XZ = plan view)
}

export interface Point3D {
  x: number
  y: number // metres, up
  z: number
}

export interface Vector3D {
  x: number
  y: number
  z: number
}

// ─── Openings ────────────────────────────────────────────────────────────────

export type OpeningType = 'window' | 'door' | 'void'

/**
 * An opening punched into a parent Surface.
 * Position is expressed in the surface's local UV coordinate space:
 *   U = horizontal axis along the surface base edge (0 = left, 1 = right)
 *   V = vertical axis (0 = bottom/sill, 1 = top/head)
 * This keeps openings resolution-independent of world geometry.
 */
export interface Opening {
  id: string
  type: OpeningType

  // Local UV position on the parent surface
  uOffset: number  // 0–1, fraction from left edge
  vOffset: number  // 0–1, fraction from bottom edge
  width: number    // metres
  height: number   // metres

  // Thermal properties (for SAP takeoff)
  uValue: number          // W/m²K
  gValue?: number         // Solar heat gain coefficient (windows only, 0–1)
  frameFactorFraction?: number // Frame factor (windows only, default 0.7)

  // Construction label for schedule
  constructionId?: string
  label?: string
}

// ─── Surfaces ────────────────────────────────────────────────────────────────

export type SurfaceType =
  | 'external_wall'
  | 'internal_partition'
  | 'party_wall'
  | 'floor_ground'      // ground-bearing slab
  | 'floor_exposed'     // exposed soffit (over external air)
  | 'floor_internal'    // floor over another heated space
  | 'ceiling_internal'  // ceiling below another heated space
  | 'roof_pitched'
  | 'roof_flat'

/** Which side of the surface faces the heat-loss boundary */
export type BoundaryCondition =
  | 'external'         // faces outside air
  | 'ground'           // faces ground
  | 'internal_heated'  // adjacent to another heated space (no heat loss)
  | 'internal_unheated'// adjacent to unheated zone (partial heat loss)
  | 'party'            // shared with another dwelling (Part L notional)
  | 'adiabatic'        // model boundary — no heat transfer

/**
 * A single planar surface belonging to a Space.
 * Geometry is defined by an ordered list of 3D vertices (convex or concave polygon).
 * Derived at extrusion time; updated if the parent Space footprint changes.
 */
export interface Surface {
  id: string
  spaceId: string       // parent Space
  type: SurfaceType
  boundaryCondition: BoundaryCondition

  // Geometry (world-space vertices, counter-clockwise when viewed from outside)
  vertices: Point3D[]
  normal: Vector3D      // outward-facing unit normal

  // Derived (recomputed from vertices — never manually set)
  grossArea: number     // m², before openings
  netArea: number       // m², after subtracting opening areas

  // Openings punched into this surface
  openings: Opening[]

  // Adjacency — populated by the Adjacency Engine
  adjacentSurfaceId?: string  // the surface on the other side (if internal/party)
  adjacentSpaceId?: string

  // Thermal construction
  constructionId?: string
  uValue?: number       // W/m²K override (else comes from constructionId lookup)

  // Orientation for SAP solar / overshading
  azimuthDeg?: number   // 0 = North, 90 = East, 180 = South, 270 = West
  tiltDeg?: number      // 0 = horizontal (floor), 90 = vertical (wall), 180 = inverted

  label?: string
}

// ─── Spaces ──────────────────────────────────────────────────────────────────

export type SpaceUseType =
  | 'habitable'
  | 'non_habitable'  // circulation, storage, utility
  | 'unheated_zone'
  | 'garage'
  | 'conservatory'

/**
 * A closed 3D polyhedral volume.
 * Defined by a 2D footprint polygon (XZ plane) + extrusion height (Y axis).
 * All Surfaces are automatically generated by the Extrusion Engine from this data.
 */
export interface Space {
  id: string
  storeyId: string
  name: string
  useType: SpaceUseType

  // 2D footprint in the storey's XZ plan view
  footprint: Point2D[]     // minimum 3 points, last point implicitly closes to first

  // Extrusion
  baseElevation: number    // Y metres — inherited from parent StoreyLayer but can be overridden
  height: number           // metres — extrusion height (typically = storey height)

  // Derived surfaces (generated by ExtrustionEngine, keyed by surface id)
  surfaces: Surface[]

  // Metadata
  floorArea: number        // m², derived from footprint (shoelace)
  volume: number           // m³, derived (floorArea × height)

  label?: string
}

// ─── Roof Planes ─────────────────────────────────────────────────────────────

export type RoofGeometryType = 'flat' | 'monopitch' | 'dualpitch_gable' | 'hip' | 'mansard' | 'dormer'

/**
 * A single planar facet of a roof assembly.
 * Roofs are stored as an array of RoofPlanes, each with its own geometry,
 * pitch, and surface properties. The Roof Generator decomposes roof types
 * into these primitives — cross-gable = 4 RoofPlanes, etc.
 */
export interface RoofPlane {
  id: string
  roofId: string           // parent Roof assembly
  label: string            // e.g. "Front Slope", "Gable End North"

  vertices: Point3D[]      // coplanar, ordered CCW from outside
  normal: Vector3D
  grossArea: number        // m²
  netArea: number          // m², after rooflights

  pitchDeg: number         // 0 = flat, 90 = vertical
  azimuthDeg: number       // direction the slope faces (downhill azimuth)

  // SAP properties
  constructionId?: string
  uValue?: number

  openings: Opening[]      // rooflights / hatches
}

export interface Roof {
  id: string
  buildingModelId: string
  geometryType: RoofGeometryType
  label: string

  // Which storey ceiling this roof sits on
  baseStoreyId: string
  baseElevation: number    // Y metres — top of the storey walls

  // Generator parameters (preserved for re-generation)
  pitchDeg: number
  ridgeOffsetFraction: number  // 0–1, where the ridge axis sits across the plan width
  eaveOverhangM: number        // horizontal overhang past the wall face

  planes: RoofPlane[]
}

// ─── Storey Layer ─────────────────────────────────────────────────────────────

/**
 * A horizontal floor level.
 * Spaces at this storey all share the same base elevation.
 * Multiple spaces per storey are supported (e.g. open-plan + stairwell).
 */
export interface StoreyLayer {
  id: string
  buildingModelId: string
  name: string             // e.g. "Ground Floor", "First Floor"
  index: number            // 0 = ground, 1 = first, etc.

  // Elevation of the floor finish level above OS datum or arbitrary origin
  baseElevation: number    // metres
  defaultHeight: number    // metres — default extrusion height for new Spaces

  spaces: Space[]
}

// ─── Adjacency ────────────────────────────────────────────────────────────────

export type AdjacencyType =
  | 'internal_partition'  // two spaces in same dwelling, same storey
  | 'internal_floor'      // floor of space above / ceiling of space below
  | 'party_wall'          // shared boundary with separate dwelling
  | 'party_floor'         // shared floor/ceiling with separate dwelling

/**
 * Created by the Adjacency Engine when two surfaces are found to be coplanar
 * and overlapping. Both surfaces are updated to BoundaryCondition 'internal_heated'
 * or 'party' accordingly.
 */
export interface Adjacency {
  id: string
  type: AdjacencyType
  surfaceAId: string
  spaceBId: string         // the space on the other side
  surfaceBId: string
  overlapArea: number      // m² — the shared area (may be partial)
}

// ─── Building Model (root) ────────────────────────────────────────────────────

export interface BuildingModel {
  id: string
  name: string
  description?: string

  // Geometry
  storeys: StoreyLayer[]
  roofs: Roof[]

  // Derived by Adjacency Engine — rebuilt on any geometry change
  adjacencies: Adjacency[]

  // Global defaults
  defaultFloorToFloorHeight: number  // metres
  defaultUValues: DefaultUValues
}

// ─── SAP Takeoff Output ───────────────────────────────────────────────────────

/**
 * All areas and properties needed for a SAP 10.2 fabric input schedule.
 * Produced by the TakeoffEngine from BuildingModel — never stored, always derived.
 */
export interface FabricElement {
  surfaceId: string
  label: string
  type: SurfaceType
  boundaryCondition: BoundaryCondition
  grossArea: number
  openingArea: number
  netArea: number
  uValue: number
  kValue?: number          // thermal mass (J/m²K) for SAP dynamic calcs
  psiValue?: number        // linear thermal bridge W/mK
  heatLossArea: number     // netArea if external/party/ground, else 0
}

export interface OpeningElement {
  openingId: string
  parentSurfaceId: string
  label: string
  type: OpeningType
  area: number             // width × height
  uValue: number
  gValue: number
  azimuthDeg: number       // inherited from parent surface
  tiltDeg: number
}

export interface StoreyTakeoff {
  storeyId: string
  storeyName: string
  floorArea: number
  volume: number
  externalWallArea: number
  internalPartitionArea: number
  partyWallArea: number
  windowArea: number
  doorArea: number
  fabricElements: FabricElement[]
  openingElements: OpeningElement[]
}

export interface BuildingTakeoff {
  totalFloorArea: number
  totalVolume: number
  totalExternalWallArea: number
  totalRoofArea: number
  totalGroundFloorArea: number
  totalWindowArea: number
  totalDoorArea: number
  averageWallUValue: number
  averageRoofUValue: number
  averageFloorUValue: number
  averageWindowUValue: number
  storeyTakeoffs: StoreyTakeoff[]
}

// ─── Construction Library ─────────────────────────────────────────────────────

export interface ConstructionLayer {
  material: string
  thicknessM: number
  conductivity: number     // W/mK
  rValue: number           // derived: thickness / conductivity
}

export interface Construction {
  id: string
  label: string
  type: SurfaceType
  layers: ConstructionLayer[]
  uValue: number           // total, including surface resistances
  kValue: number           // J/m²K
}

// ─── UI / Editor State ────────────────────────────────────────────────────────

export type DrawingTool =
  | 'select'
  | 'draw_space'      // draw 2D footprint → extrude to Space
  | 'draw_opening'    // click on a Surface to enter Surface View and place Opening
  | 'split_surface'   // draw a line across a Surface to subdivide it

export type ViewMode =
  | 'plan'            // top-down 2D view, shows XZ footprints
  | 'surface'         // face-on 2D view of a single selected Surface (for opening placement)
  | '3d'              // orbit 3D preview

export interface SelectionState {
  storeyId?: string
  spaceId?: string
  surfaceId?: string
  openingId?: string
  roofPlaneId?: string
}

export interface EditorState {
  activeStoreyId: string | null
  selection: SelectionState
  viewMode: ViewMode
  drawingTool: DrawingTool
  gridSizeM: number
  snapToGrid: boolean
  snapToAngle: boolean   // 45° increments
  showAdjacencies: boolean
  showOpenings: boolean
}

// ─── Defaults ────────────────────────────────────────────────────────────────

export interface DefaultUValues {
  externalWall: number     // W/m²K
  roof: number
  groundFloor: number
  window: number
  door: number
  partyWall: number        // SAP notional = 0.0 (no heat loss across party)
  internalPartition: number
}

export const SAP_NOTIONAL_UVALUES: DefaultUValues = {
  externalWall: 0.18,
  roof: 0.11,
  groundFloor: 0.13,
  window: 1.4,
  door: 1.4,
  partyWall: 0.0,
  internalPartition: 0.0,
}

// ─── Engine interfaces ────────────────────────────────────────────────────────

/**
 * ExtrusionEngine: takes a Space's footprint + height and returns
 * a fully populated surfaces array (floor + ceiling + N walls).
 */
export interface ExtrusionResult {
  floor: Surface
  ceiling: Surface
  walls: Surface[]   // one per footprint edge, in footprint vertex order
}

/**
 * AdjacencyEngine input: all spaces across all storeys.
 * Returns adjacency records and a map of surfaceId → new BoundaryCondition.
 */
export interface AdjacencyResult {
  adjacencies: Adjacency[]
  surfaceBoundaryUpdates: Map<string, BoundaryCondition>
}

/**
 * RoofGenerator input parameters.
 */
export interface RoofGeneratorInput {
  geometryType: RoofGeometryType
  footprint: Point2D[]       // plan polygon of the roof (usually top storey footprint)
  baseElevation: number      // Y metres — eaves height
  pitchDeg: number
  ridgeOffsetFraction?: number  // for dualpitch_gable / hip
  eaveOverhangM?: number
  dormerInputs?: DormerInput[]
}

export interface DormerInput {
  wallEdgeIndex: number      // which wall edge the dormer sits on
  widthM: number
  heightM: number
  uOffsetFraction: number    // position along that wall edge (0–1)
}
